documentums/config/routes.rb
Documentum::Application.routes.draw do
  resources :branches

  resources :chairs

  resources :users

  resources :types

  resources :reasons

  resources :documents
  
  resources :type do 
    resources :documents do 
    end
  end

  resources :branch do 
    resources :documents do 
    end
  end

  resources :chair do 
    resources :documents do 
    end
  end
 
  resources :reason_documents_path
  
  resources :type_documents_path
  

   root :to => 'documents#index'

end

documentums/app/views/layouts/_aside.haml
#aside.box
  .padding.box

documentums/app/views/layouts/_footer.haml
#footer.box
  %p.f-left

documentums/app/views/layouts/_menu.haml
#menu.box
  %ul.box
    %li{:id=>controller_name=='documents' ? "menu-active" : nil}=link_to content_tag(:span,"Приказы"),documents_path
    %li{:id=>controller_name=='types' ? "menu-active" : nil}=link_to content_tag(:span,"Типы"),types_path
    %li{:id=>controller_name=='reasons' ? "menu-active" : nil}=link_to content_tag(:span,"Основания"),reasons_path
    %li{:id=>controller_name=='users' ? "menu-active" : nil}=link_to content_tag(:span,"Пользователи"),users_path
    %li{:id=>controller_name=='chairs' ? "menu-active" : nil}=link_to content_tag(:span,"Кафедры"),chairs_path
    %li{:id=>controller_name=='branches' ? "menu-active" : nil}=link_to content_tag(:span,"Специальности"),branches_path

documentums/app/views/layouts/_tray.haml
#tray.box
  %p.box.f-left
    
    

documentums/app/views/layouts/application.haml
!!!
%html
  %head
    %title Документооборот
    = stylesheet_link_tag 'reset', 'main', '2col', 'style', 'mystyle','token-input-facebook'      
    /[if lte IE 6]
    =stylesheet_link_tag 'main-ie6'
    =javascript_include_tag  'jquery', 'jquery.min', 'jquery.tokeninput','rails', 'application', 'jquery.grewform.js'
    = csrf_meta_tag
  %body
    #main
      = render 'layouts/tray'
      %hr.noscreen
      = render 'layouts/menu'
      %hr.noscreen
      #cols.box
        = render 'layouts/aside'
        %hr.noscreen
        #content.box
          -unless notice.blank?
            .msg.done=notice
          -unless flash[:error].blank?
            .msg.error=flash[:error]
          = yield
      %hr.noscreen
      = render 'layouts/footer'