documentums/config/routes.rb
Documentum::Application.routes.draw do
  resources :branches

  resources :chairs

  resources :users

  resources :types

  resources :reasons

  resources :documents
  
  resources :type do 
    resources :documents do 
    end
  end

  resources :branch do 
    resources :documents do 
    end
  end

  resources :chair do 
    resources :documents do 
    end
  end
 
  resources :reason_documents_path
  
  resources :type_documents_path
  

   root :to => 'documents#index'

end

documentums/app/models/chair.rb
class Chair < ActiveRecord::Base
  has_many :documents,:order=>'name'
  
  default_scope order(:name)
  
  validates :name,:presence => true,:uniqueness => true

end

documentums/app/controllers/chairs_controller.rb
class ChairsController < ApplicationController
  # GET /chairs
  # GET /chairs.json
  def index
    @chairs = Chair.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chairs }
    end
  end

  # GET /chairs/1
  # GET /chairs/1.json
  def show
    @chair = Chair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chair }
    end
  end

  # GET /chairs/new
  # GET /chairs/new.json
  def new
    @chair = Chair.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chair }
    end
  end

  # GET /chairs/1/edit
  def edit
    @chair = Chair.find(params[:id])
  end

  # POST /chairs
  # POST /chairs.json
  def create
    @chair = Chair.new(params[:chair])

    respond_to do |format|
      if @chair.save
        format.html { redirect_to @chair, notice: 'Chair was successfully created.' }
        format.json { render json: @chair, status: :created, location: @chair }
      else
        format.html { render action: "new" }
        format.json { render json: @chair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chairs/1
  # PUT /chairs/1.json
  def update
    @chair = Chair.find(params[:id])

    respond_to do |format|
      if @chair.update_attributes(params[:chair])
        format.html { redirect_to @chair, notice: 'Chair was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @chair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chairs/1
  # DELETE /chairs/1.json
  def destroy
    @chair = Chair.find(params[:id])
    @chair.destroy

    respond_to do |format|
      format.html { redirect_to chairs_url }
      format.json { head :ok }
    end
  end
end

documentums/app/helpers/chairs_helper.rb
module ChairsHelper
end

documentums/app/views/chairs/_form.html.haml
= form_for @chair do |f|
  -if @chair.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chair.errors.count, "error")} prohibited this chair from being saved:"
      %ul
        - @chair.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :number
    = f.text_field :number
  .actions
    = f.submit 'Save'

documentums/app/views/chairs/edit.html.haml
%h1 Editing chair

= render 'form'

= link_to 'Show', @chair
\|
= link_to 'Back', chairs_path

documentums/app/views/chairs/index.html.haml
%h1 Listing chairs

%table
  %tr
    %th Name
    %th Number
    %th
    %th
    %th

  - @chairs.each do |chair|
    %tr
      %td= chair.name
      %td= chair.number
      %td= link_to 'Show', chair
      %td= link_to 'Edit', edit_chair_path(chair)
      %td= link_to 'Destroy', chair, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Chair', new_chair_path

documentums/app/views/chairs/new.html.haml
%h1 New chair

= render 'form'

= link_to 'Back', chairs_path

documentums/app/views/chairs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @chair.name
%p
  %b Number:
  = @chair.number

= link_to 'Edit', edit_chair_path(@chair)
\|
= link_to 'Back', chairs_path