documentums/config/routes.rb
Documentum::Application.routes.draw do
  resources :branches

  resources :chairs

  resources :users

  resources :types

  resources :reasons

  resources :documents
  
  resources :type do 
    resources :documents do 
    end
  end

  resources :branch do 
    resources :documents do 
    end
  end

  resources :chair do 
    resources :documents do 
    end
  end
 
  resources :reason_documents_path
  
  resources :type_documents_path
  

   root :to => 'documents#index'

end

documentums/app/models/document.rb
# coding: utf-8

class Document < ActiveRecord::Base
  scope :full_load, includes(:reason, :type, :users, :branch, :chair)
  serialize :settings
  
  belongs_to :reason
  belongs_to :type
  belongs_to :branch
  belongs_to :chair
  has_and_belongs_to_many :users
  

  validates :number,:presence => true,
                    :length   => { :within => 1..10 }
  validates :type_id,:presence => true
  
  validates :cdate,:presence => true

  attr_reader :user_tokens
  
  def user_tokens=(ids)
    self.user_ids = ids.split(",")
  end
  
end

documentums/app/controllers/documents_controller.rb
# coding: utf-8

class DocumentsController < ApplicationController

  def index
#    raise "ID = #{params[:id]}"
    @documents = !params[:type_id].blank?  ?  Document.where(:type_id => params[:type_id].to_i)  :  Document.all
    @type = Type.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @documents }
    end
  end

  def show       
    doc = Document.full_load.find(params[:id]) 
    @doc_type = doc.type.name
    @doc_number = doc.number
#    @document = Document.where("number = '" + doc.number + "' and cdate = #{doc.cdate} and type_id = #{doc.type_id}")                
    @document = Document.where("number = '" + doc.number + "' and type_id = #{doc.type_id}")
    
    respond_to do |format|
      format.html
      format.pdf
    end
  end
  
  def new
    @document = Document.new
  end

  def edit
    @document = Document.full_load.find(params[:id])
  end

  def create
    @document = Document.new(params[:document])
    res = Reason.new(:name => @document.reas)
    usr = User.new(:name => @document.user_name,:surname => @document.user_surname,:middlename => @document.user_middlename)

    if @document.save | res.save | usr.save
      redirect_to @document, :notice => 'Приказ добавлен.'
    else
      render :action => "new"
    end
  end

  def update
    @document = Document.find(params[:id])
    res = Reason.new(:name => @document.reas)
    usr = User.new(:name => @document.user_name,:surname => @document.user_surname,:middlename => @document.user_middlename)

    if @document.update_attributes(params[:document]) | res.update_attributes(params[:document]) | usr.update_attributes(params[:document])
      redirect_to @document, :notice => 'Приказ сохранен.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end
end

documentums/app/helpers/documents_helper.rb
# coding: utf-8

module DocumentsHelper
   def type_change
    "Приказ о смене специальности, факультета, кафедры"
   end
   
   def type_delete
    "Приказ об отчислении из аспирантуры"
   end
   
   def type_enroll
    "Приказ о зачислении в аспирантуру"
   end
   
   def type_transfer
    "Приказ о переводе на другую форму обучения"
   end
end

documentums/app/views/documents/_chan_show.html.haml
#document_wrapper
  #document_header
    Федеральное государственное бюджетное
    образовательное учреждение высшего профессионального образования 
    %br
    московский государственный индустриальный университет
    %br
    (ФГБОУ ВПО МГИУ)
    #document_name
      = '№ ' + @doc_number
    -@document.each do |document|
      %br
      =document.type.name
      %br

documentums/app/views/documents/_del_show.html.haml
#document_wrapper
  #document_header
    Федеральное государственное бюджетное
    образовательное учреждение высшего профессионального образования 
    %br
    московский государственный индустриальный университет
    %br
    (ФГБОУ ВПО МГИУ)
    #document_name
      = '№ ' + @doc_number
    -@document.each do |document|
    
      %br
      =document.type.name
      %br

documentums/app/views/documents/_en_form.html.haml
.field
  = f.label :user_name, "Имя"
  = f.text_field :user_name
  = f.label :user_surname, "Фамилия"
  = f.text_field :user_surname
  = f.label :user_middlename, "Отчество"
  = f.text_field :user_middlename
.field
  = f.label :name, "Научная специальность"
  = f.select :branch_id, Branch.all.map{|b| [b.name,b.id]}
.field
  = f.label :body, "Научный руководитель"
  = f.text_field :body
.field
  = f.label :chair_id, "Кафедра"
  = f.select :chair_id, Chair.all.map{|c| [c.name,c.id]}
.field
  = f.label :sdate, "Дата зачисления хлопцэв"
  = f.date_select :sdate

documentums/app/views/documents/_en_show.html.haml
#document_wrapper
  #document_header
    Федеральное государственное бюджетное
    образовательное учреждение высшего профессионального образования 
    %br
    московский государственный индустриальный университет
    %br
    (ФГБОУ ВПО МГИУ)
    #document_name
      = '№ ' + @doc_number
    -@document.each do |document|
      %br
      =document.type.name
      %br
      -document.users.each do |users|
        = users.surname

documentums/app/views/documents/_form.html.haml
= form_for(@document) do |f|
  - if @document.errors.any?
    .msg.error
      %h2= "При сохранении произошли ошибки"
      %ul
        - @document.errors.full_messages.each do |msg|
          %li= msg
  .film
    .col
      .field
        = f.label :number, "Номер"
        = f.text_field :number
        = f.label :cdate
        = f.date_select :cdate
      .field
        = f.label :name, "Тип приказа"
        = f.select :type_id, Type.all.map{|t| [t.name,t.id]}
        
      .clear
  .film
    .col
    #reason_en_form
      .field
        = f.label :user_name, "Имя"
        = f.text_field :user_name
        = f.label :user_surname, "Фамилия"
        = f.text_field :user_surname
        = f.label :user_middlename, "Отчество"
        = f.text_field :user_middlename
      .field
        = f.label :name, "Научная специальность"
        = f.select :branch_id, Branch.all.map{|b| [b.name,b.id]}
      .field
        = f.label :body, "Научный руководитель"
        = f.text_field :body
      .field
        = f.label :chair_id, "Кафедра"
        = f.select :chair_id, Chair.all.map{|c| [c.name,c.id]}
      .field
        = f.label :sdate, "Дата зачисления хлопцэв"
        = f.date_select :sdate
  
    #reason_trans_form
      .field
        = f.label :body, "Форма обучения"
        = f.text_field :body
  
    #reason_chan_form
      .field
        = f.label :name, "Научная специальность"
        = f.select :branch_id, Branch.all.map{|b| [b.name,b.id]}
      .field
        = f.label :chair_id, "Кафедра"
        = f.select :chair_id, Chair.all.map{|c| [c.name,c.id]}
      .field
        = f.label :body, "Факультет"
        = f.text_field :body
    
    #reason_del_form
      .field
        = f.label :reason_tokens, "Основание"
        = f.select :reason_id, Reason.all.map{|r| [r.name,r.id]},{}, :onclick => "document.getElementById('document_reas').value = getSelectedText(this.id);"
      .field
        = f.text_field :reas
      .field
        = f.label :sdate
        %br
        = f.date_select :sdate
      .field
        = f.label :comment
        = f.text_area :comment
      
    .field
      = f.label :user_tokens, "Пасаны"
      = f.text_field :user_tokens, "data-pre"=>@document.users.map(&:attributes).to_json
    .clear
  
  
  
  .actions
    = f.submit 'Сохранить'

documentums/app/views/documents/_transfer_show.html.haml
#document_wrapper
  #document_header
    Федеральное государственное бюджетное
    образовательное учреждение высшего профессионального образования 
    %br
    московский государственный индустриальный университет
    %br
    (ФГБОУ ВПО МГИУ)
    #document_name
      = '№ ' + @doc_number
    -@document.each do |document|
      %br
      =document.type.name
      %br
    

documentums/app/views/documents/edit.html.haml
%h1 Редактировать приказ

#mod_form
  = render 'form'

  = link_to 'Показать', @document
  \|
  = link_to 'Назад', documents_path

documentums/app/views/documents/index.html.haml
%tbody
  - @type.each do |type|
    %tr
      %td= link_to type.name, type_documents_path(type)
      %br
          
          
          

%h1 Документы
%table
  %thead
    %tr
      %th №
      %th Номер
      %th Тип
      %th Дата создания
      %th Состояние
      %th Аспиранты
      %th Просмотреть
  %tbody
    -i=0
    - @documents.each do |document|
      %tr
        %td= i+=1
        %td= link_to document.number, document_path(document)
        %td= document.type.name
        %td= document.cdate
        %td= document.dstate
        
        %td
          -document.users.each do |users|
            = users.surname + ' ' + users.name
            %br
        %td
          = link_to "HTML", document_path(document)
          %br
          = link_to "PDF", document_path(document,:format => :pdf)
          %br
          = link_to 'Редактировать', edit_document_path(document)
          %br
          = link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete
       
.actions
  = link_to 'Новый документ', new_document_path, :class=>"btn primary"

documentums/app/views/documents/new.html.haml
%h1 Новый приказ

#mod_form
  = render 'form'

  = link_to 'Назад', documents_path

documentums/app/views/documents/show.html.haml
%h1=@doc_type
.film
  .col
    %dl
      - if @doc_type == type_enroll
        = render 'en_show'
      -elsif @doc_type == type_transfer
        = render 'transfer_show'
      -elsif @doc_type == type_change
        = render 'chan_show'
      -elsif @doc_type == type_delete
        = render 'del_show'
        
  .clear
  
= link_to "Назад", documents_path


documentums/app/views/documents/show.pdf.erb
\vspace*{-\headheight}\vspace*{-\headsep}

{\centering\textsc{ 
Федеральное государственное бюджетное\\
образовательное учреждение высшего профессионального\\
образования московский государственный индустриальный университет\\
(ФГБОУ ВПО МГИУ)
}