documentums/config/routes.rb
Documentum::Application.routes.draw do
  resources :branches

  resources :chairs

  resources :users

  resources :types

  resources :reasons

  resources :documents
  
  resources :type do 
    resources :documents do 
    end
  end

  resources :branch do 
    resources :documents do 
    end
  end

  resources :chair do 
    resources :documents do 
    end
  end
 
  resources :reason_documents_path
  
  resources :type_documents_path
  

   root :to => 'documents#index'

end

documentums/app/controllers/types_controller.rb
# -*- coding: utf-8 -*-
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :ok }
    end
  end
end

documentums/app/helpers/types_helper.rb
module TypesHelper
end

documentums/app/views/types/_form.html.haml
= form_for @type do |f|
  -if @type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@type.errors.count, "error")} prohibited this type from being saved:"
      %ul
        - @type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

documentums/app/views/types/edit.html.haml
%h1 Editing type

= render 'form'

= link_to 'Show', @type
\|
= link_to 'Back', types_path

documentums/app/views/types/index.html.haml
%h1 Типы приказов

%table
  %tr
    %th Наименование
    %th
    %th
    %th

  - @types.each do |type|
    %tr
      %td= type.name
      %td= link_to 'Показать', type
      %td= link_to 'Редактировать', edit_type_path(type)
      %td= link_to 'Удалить', type, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'Новый тип', new_type_path

documentums/app/views/types/new.html.haml
%h1 New type

= render 'form'

= link_to 'Back', types_path

documentums/app/views/types/show.html.haml
%p#notice= notice

%p
  %b Наименование:
  %br
  = @type.name
  

= link_to 'Редактировать', edit_type_path(@type)
\|
= link_to 'Название', types_path